"""
Django settings for event project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8p$uc&*%(4h(44j$hlt2a#cke%37r68--r^xk70v+3j+58gts%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['35.247.133.29','first-api.respirer.in','www.first-api.respirer.in']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'ticket',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'event.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'event.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default':{
#         'ENGINE':'django.db.backends.postgresql_psycopg2',
#         'NAME': 'newdb',
#         'USER':'postgres',
#         'PASSWORD': '12345',
#         'HOST':'localhost',
#         'PORT':'5432'

#     }
# }

DATABASES = {
    'default':{
        'ENGINE':'django.db.backends.postgresql_psycopg2',
        'NAME': 'myproject',
        'USER':'myprojectuser',
        'PASSWORD': 'kyadekhoge',
        'HOST':'localhost',
        'PORT':'5432'
    }
}

# sudo nano /etc/systemd/system/respirer.in.gunicorn.socket
# sudo nano /etc/systemd/system/respirer.in.gunicorn.service



# Example:- 
# [Unit]
# Description=respirer.in.gunicorn socket

# [Socket]
# ListenStream=/run/respirer.in.gunicorn.sock

# [Install]
# WantedBy=sockets.target


# [Unit]
# Description=respirer.in.gunicorn daemon
# Requires=respirer.in.gunicorn.socket
# After=network.target

# [Service]
# User=root
# Group=groupname
# WorkingDirectory=/home/ubuntu/booking/event
# ExecStart=/home/ubuntu/booking/event/venv/bin/gunicorn \
#           --access-logfile - \
#           --workers 3 \
#           --bind unix:/run/respirer.in.gunicorn.sock \
#           event.wsgi:application

# [Install]
# WantedBy=multi-user.target


# server{
#     listen 80;
#     listen [::]:80;

#     server_name first-api.respirer.in www.first-api.respirer.in;

#     location = /favicon.ico { access_log off; log_not_found off; }

#     location / {
#         proxy_set_header Host $http_host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#         proxy_pass http://unix:/run/respirer.in.gunicorn.sock;
#     }

#     location  /static/ {
#         root /var/www/event;
#     }

#     location  /media/ {
#         root /var/www/event;
#     }
# }

# sudo ln -s /etc/nginx/sites-available/respirer.in /etc/nginx/sites-enabled/respirer.in


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
