# Generated by Django 5.2.4 on 2025-07-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled'), ('Happening', 'Happening')], default='Upcoming', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular')], max_length=255),
        ),
    ]
