# Generated by Django 5.2.4 on 2025-07-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_event_status_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
