# Generated by Django 5.2.4 on 2025-07-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
